In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\manoj\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\manoj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [1]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')
print(df)

      Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]

In [13]:
df.columns=df.columns.str.lower()

In [14]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [15]:
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [17]:
print(df.head(20))

    customer_id  age gender item_purchased     category  purchase_amount_usd  \
0             1   55   Male         Blouse     Clothing                   53
1             2   19   Male        Sweater     Clothing                   64
2             3   50   Male          Jeans     Clothing                   73
3             4   21   Male        Sandals     Footwear                   90
4             5   45   Male         Blouse     Clothing                   49
5             6   46   Male       Sneakers     Footwear                   20
6             7   63   Male          Shirt     Clothing                   85
7             8   27   Male         Shorts     Clothing                   34
8             9   26   Male           Coat    Outerwear                   97
9            10   57   Male        Handbag  Accessories                   31
10           11   53   Male          Shoes     Footwear                   34
11           12   30   Male         Shorts     Clothing                   68
12           13   61   Male           Coat    Outerwear                   72
13           14   65   Male          Dress     Clothing                   51
14           15   64   Male           Coat    Outerwear                   53
15           16   64   Male          Skirt     Clothing                   81
16           17   25   Male     Sunglasses  Accessories                   36
17           18   53   Male          Dress     Clothing                   38
18           19   52   Male        Sweater     Clothing                   48
19           20   66   Male          Pants     Clothing                   90

         location size      color  season  review_rating subscription_status  \
0        Kentucky    L       Gray  Winter            3.1                 Yes
1           Maine    L     Maroon  Winter            3.1                 Yes
2   Massachusetts    S     Maroon  Spring            3.1                 Yes
3    Rhode Island    M     Maroon  Spring            3.5                 Yes
4          Oregon    M  Turquoise  Spring            2.7                 Yes
5         Wyoming    M      White  Summer            2.9                 Yes
6         Montana    M       Gray    Fall            3.2                 Yes
7       Louisiana    L   Charcoal  Winter            3.2                 Yes
8   West Virginia    L     Silver  Summer            2.6                 Yes
9        Missouri    M       Pink  Spring            4.8                 Yes
10       Arkansas    L     Purple    Fall            4.1                 Yes
11         Hawaii    S      Olive  Winter            4.9                 Yes
12       Delaware    M       Gold  Winter            4.5                 Yes
13  New Hampshire    M     Violet  Spring            4.7                 Yes
14       New York    L       Teal  Winter            4.7                 Yes
15   Rhode Island    M       Teal  Winter            2.8                 Yes
16        Alabama    S       Gray  Spring            4.1                 Yes
17    Mississippi   XL   Lavender  Winter            4.7                 Yes
18        Montana    S      Black  Summer            4.6                 Yes
19   Rhode Island    M      Green  Summer            3.3                 Yes

     shipping_type discount_applied promo_code_used  previous_purchases  \
0          Express              Yes             Yes                  14
1          Express              Yes             Yes                   2
2    Free Shipping              Yes             Yes                  23
3     Next Day Air              Yes             Yes                  49
4    Free Shipping              Yes             Yes                  31
5         Standard              Yes             Yes                  14
6    Free Shipping              Yes             Yes                  49
7    Free Shipping              Yes             Yes                  19
8          Express              Yes             Yes                   8
9   2-Day Shipping              Yes             Yes                   4
10    Store Pickup              Yes             Yes                  26
11    Store Pickup              Yes             Yes                  10
12         Express              Yes             Yes                  37
13         Express              Yes             Yes                  31
14   Free Shipping              Yes             Yes                  34
15    Store Pickup              Yes             Yes                   8
16    Next Day Air              Yes             Yes                  44
17  2-Day Shipping              Yes             Yes                  36
18   Free Shipping              Yes             Yes                  17
19        Standard              Yes             Yes                  46

   payment_method frequency_of_purchases
0           Venmo            Fortnightly
1            Cash            Fortnightly
2     Credit Card                 Weekly
3          PayPal                 Weekly
4          PayPal               Annually
5           Venmo                 Weekly
6            Cash              Quarterly
7     Credit Card                 Weekly
8           Venmo               Annually
9            Cash              Quarterly
10  Bank Transfer              Bi-Weekly
11  Bank Transfer            Fortnightly
12          Venmo            Fortnightly
13         PayPal                 Weekly
14     Debit Card                 Weekly
15         PayPal                Monthly
16     Debit Card              Bi-Weekly
17          Venmo              Quarterly
18           Cash                 Weekly
19     Debit Card              Bi-Weekly

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3863 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   object
 17  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [26]:
print(df.describe())

       customer_id          age  purchase_amount  review_rating  \
count  3900.000000  3900.000000      3900.000000    3863.000000
mean   1950.500000    44.068462        59.764359       3.750065
std    1125.977353    15.207589        23.685392       0.716983
min       1.000000    18.000000        20.000000       2.500000
25%     975.750000    31.000000        39.000000       3.100000
50%    1950.500000    44.000000        60.000000       3.800000
75%    2925.250000    57.000000        81.000000       4.400000
max    3900.000000    70.000000       100.000000       5.000000

       previous_purchases
count         3900.000000
mean            25.351538
std             14.447125
min              1.000000
25%             13.000000
50%             25.000000
75%             38.000000
max             50.000000

In [18]:
print(df.isnull().sum())

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_usd        0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [19]:
print(df['review_rating'])

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: review_rating, Length: 3900, dtype: float64

In [21]:
df["review_rating"]=df.groupby('category')["review_rating"].transform(lambda x:x.fillna(x.median()))

In [22]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_usd       0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [23]:
print(df[['discount_applied','promo_code_used']].head())

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [24]:
#comparing two column values for each row
(df['discount_applied']==df['promo_code_used']).all()

True

In [25]:
df=df.drop('promo_code_used',axis=1)

In [26]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [28]:
df['frequency_of_purchases']

0       Fortnightly
1       Fortnightly
2            Weekly
3            Weekly
4          Annually
           ...
3895         Weekly
3896      Bi-Weekly
3897      Quarterly
3898         Weekly
3899      Quarterly
Name: frequency_of_purchases, Length: 3900, dtype: object

In [29]:
# creating new column
labels={ 'Bi-Weekly':14,
        'Weekly':7,
        'Monthly':30,
        'Quarterly':90,
        'every 3 months':90,
        'Annually':365,
        'Fortnightly':14
       }
        
df['purchase_frequency_days']=df['frequency_of_purchases'].map(labels)

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'purchase_frequency_days'],
      dtype='object')

In [31]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                        14.0            Fortnightly
1                        14.0            Fortnightly
2                         7.0                 Weekly
3                         7.0                 Weekly
4                       365.0               Annually
...                       ...                    ...
3895                      7.0                 Weekly
3896                     14.0              Bi-Weekly
3897                     90.0              Quarterly
3898                      7.0                 Weekly
3899                     90.0              Quarterly

[3900 rows x 2 columns]

In [32]:
df['purchase_frequency_days'].isnull().all()

False

In [33]:
labels=['young_adult','adult','middle','old']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [34]:
df['age_group'].head(10)

0         middle
1    young_adult
2         middle
3    young_adult
4         middle
5         middle
6            old
7    young_adult
8    young_adult
9         middle
Name: age_group, dtype: category
Categories (4, object): ['young_adult' < 'adult' < 'middle' < 'old']

In [35]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'purchase_frequency_days', 'age_group'],
      dtype='object')

In [38]:
#mysql connector installed
!pip install mysql-connector-python pandas

Requirement already satisfied: mysql-connector-python in c:\users\manoj\anaconda3\lib\site-packages (26.7.0)
Requirement already satisfied: pandas in c:\users\manoj\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manoj\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\manoj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [39]:
import mysql.connector

In [45]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="071104",
    database="customer_b_analysis"
)

print(connection.is_connected())

True

In [41]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\manoj\anaconda3\lib\site-packages (2.0.34)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\manoj\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\manoj\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [46]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:071104@localhost/customer_b_analysis"
)

In [47]:
df.to_sql(
    'customer',
    con=engine,
    if_exists='replace',
    index=False
)

-1

In [44]:
pd.read_sql(
    "select * from customer limit 10",
    engine
)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,purchase_frequency_days,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,14.0,middle
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,14.0,young_adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,7.0,middle
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,7.0,young_adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,365.0,middle
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,7.0,middle
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,90.0,old
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,7.0,young_adult
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,365.0,young_adult
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,90.0,middle

In [8]:
df.rename(columns={
    'Customer ID': 'customer_id',
    'Age': 'age',
    'Gender': 'gender',
    'Item Purchased': 'item_purchased',
    'Category': 'category',
    'Purchase Amount (USD)': 'purchase_amount_usd',
    'Location': 'location',
    'Size': 'size',
    'Color': 'color',
    'Season': 'season',
    'Review Rating': 'review_rating',
    'Subscription Status': 'subscription_status',
    'Shipping Type': 'shipping_type',
    'Discount Applied': 'discount_applied',
    'Promo Code Used': 'promo_code_used',
    'Previous Purchases': 'previous_purchases',
    'Payment Method': 'payment_method',
    'Frequency of Purchases': 'frequency_of_purchases'
}, inplace=True)

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
df.to_sql(
    'customer',
    con=engine,
    if_exists='replace',
    index=False
)

-1

In [12]:
pd.read_sql('select * from customer',engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly